[package]
name = "kafka-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = { version = "0.36.2", features = ["ssl", "cmake-build"] }
tokio = { version = "1.41.1", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.5"
futures = "0.3.31"
reqwest = "0.12.9"
config = "0.14.0"
serde_derive = "1.0.215"
derive-getters = "0.5.0"
serde = { version = "1.0", features = ["derive"] }
