[package]
name = "kafka-processor"
version = "0.1.0"
edition = "2021"

[dependencies]
rdkafka = "0.36.2"
tokio = { version = "1.41.1", features = ["full"] }
log = "0.4.22"
env_logger = "0.11.5"
futures = "0.3.31"
reqwest = "0.12.9"
