[package]
name = "flint"
version = "0.1.0"
edition = "2024"

[dependencies]
rdkafka = { version = "0.38.0", features = ["ssl", "cmake-build", "tracing"] }
tokio = { version = "1.52.3", features = ["full"] }
log = "0.4.32"
env_logger = "0.11.10"
tracing-subscriber = { version = "0.3.23", features = ["env-filter"] }
futures = "0.3.32"
reqwest = { version = "0.13.4", features = ["json"] }
config = "0.15.23"
serde_derive = "1.0.228"
serde = { version = "1.0.228", features = ["derive"] }
reqwest-retry = "0.9.1"
reqwest-middleware = "0.5.2"
tokio-util = "0.7.18"
serde_json = "1.0.150"
anyhow = "1.0.102"
thiserror = "2.0.18"

[dev-dependencies]
httpmock = "0.8.3"
